# Lecture 3

## Numpy

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [4]:
a2 = a[np.newaxis, :]

In [5]:
a2

array([[0, 1, 2, 3, 4, 5]])

### How to create a basic array

This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [6]:
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)

In [15]:
x

array([1, 1])

### Adding, removing, and sorting elements

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [19]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### Shape


In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [23]:
array_example.ndim

3

In [24]:
array_example.size

24

In [25]:
array_example.shape

(3, 2, 4)

### Can you reshape an array?

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [30]:
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

In [31]:
row_vector = a[np.newaxis, :]
row_vector.shape


(1, 6)

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape


(6,)

In [41]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [42]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and slicing

In [43]:
data = np.array([1, 2, 3])

In [44]:
data[0:2]

array([1, 2])

In [45]:
data[1:]

array([2, 3])

In [46]:
data[-2:]

array([2, 3])

In [47]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [48]:
print(a[a < 5])

[1 2 3 4]


In [49]:
five_up = (a >= 5)

In [50]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [51]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)


[ 2  4  6  8 10 12]


In [53]:
c = a[(a > 2) & (a < 11)]

In [54]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
c[np.nonzero(c)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [57]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [59]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [61]:
np.vstack((a1, a2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [62]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [67]:
a1.view()

array([[1, 1],
       [2, 2]])